#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Web.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Cerberus")]
	public partial class CerberusDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEFTTerminalAudit(EFTTerminalAudit instance);
    partial void UpdateEFTTerminalAudit(EFTTerminalAudit instance);
    partial void DeleteEFTTerminalAudit(EFTTerminalAudit instance);
    #endregion
		
		public CerberusDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CerberusConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CerberusDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CerberusDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CerberusDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CerberusDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EFTTerminalAudit> EFTTerminalAudits
		{
			get
			{
				return this.GetTable<EFTTerminalAudit>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EFTTerminalAudit")]
	public partial class EFTTerminalAudit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PinPadId;
		
		private string _Make;
		
		private string _Model;
		
		private System.Nullable<long> _MerchantId;
		
		private string _TerminalId;
		
		private string _SWVersion;
		
		private int _OfficeNo;
		
		private System.Nullable<int> _StationNo;
		
		private System.Nullable<System.DateTime> _FirstVerified;
		
		private System.Nullable<System.DateTime> _LastVerified;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPinPadIdChanging(long value);
    partial void OnPinPadIdChanged();
    partial void OnMakeChanging(string value);
    partial void OnMakeChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnMerchantIdChanging(System.Nullable<long> value);
    partial void OnMerchantIdChanged();
    partial void OnTerminalIdChanging(string value);
    partial void OnTerminalIdChanged();
    partial void OnSWVersionChanging(string value);
    partial void OnSWVersionChanged();
    partial void OnOfficeNoChanging(int value);
    partial void OnOfficeNoChanged();
    partial void OnStationNoChanging(System.Nullable<int> value);
    partial void OnStationNoChanged();
    partial void OnFirstVerifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnFirstVerifiedChanged();
    partial void OnLastVerifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastVerifiedChanged();
    #endregion
		
		public EFTTerminalAudit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PinPadId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long PinPadId
		{
			get
			{
				return this._PinPadId;
			}
			set
			{
				if ((this._PinPadId != value))
				{
					this.OnPinPadIdChanging(value);
					this.SendPropertyChanging();
					this._PinPadId = value;
					this.SendPropertyChanged("PinPadId");
					this.OnPinPadIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Make", DbType="NVarChar(10)")]
		public string Make
		{
			get
			{
				return this._Make;
			}
			set
			{
				if ((this._Make != value))
				{
					this.OnMakeChanging(value);
					this.SendPropertyChanging();
					this._Make = value;
					this.SendPropertyChanged("Make");
					this.OnMakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(10)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MerchantId", DbType="BigInt")]
		public System.Nullable<long> MerchantId
		{
			get
			{
				return this._MerchantId;
			}
			set
			{
				if ((this._MerchantId != value))
				{
					this.OnMerchantIdChanging(value);
					this.SendPropertyChanging();
					this._MerchantId = value;
					this.SendPropertyChanged("MerchantId");
					this.OnMerchantIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerminalId", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string TerminalId
		{
			get
			{
				return this._TerminalId;
			}
			set
			{
				if ((this._TerminalId != value))
				{
					this.OnTerminalIdChanging(value);
					this.SendPropertyChanging();
					this._TerminalId = value;
					this.SendPropertyChanged("TerminalId");
					this.OnTerminalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWVersion", DbType="NVarChar(16)")]
		public string SWVersion
		{
			get
			{
				return this._SWVersion;
			}
			set
			{
				if ((this._SWVersion != value))
				{
					this.OnSWVersionChanging(value);
					this.SendPropertyChanging();
					this._SWVersion = value;
					this.SendPropertyChanged("SWVersion");
					this.OnSWVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OfficeNo
		{
			get
			{
				return this._OfficeNo;
			}
			set
			{
				if ((this._OfficeNo != value))
				{
					this.OnOfficeNoChanging(value);
					this.SendPropertyChanging();
					this._OfficeNo = value;
					this.SendPropertyChanged("OfficeNo");
					this.OnOfficeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationNo", DbType="Int")]
		public System.Nullable<int> StationNo
		{
			get
			{
				return this._StationNo;
			}
			set
			{
				if ((this._StationNo != value))
				{
					this.OnStationNoChanging(value);
					this.SendPropertyChanging();
					this._StationNo = value;
					this.SendPropertyChanged("StationNo");
					this.OnStationNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstVerified", DbType="DateTime")]
		public System.Nullable<System.DateTime> FirstVerified
		{
			get
			{
				return this._FirstVerified;
			}
			set
			{
				if ((this._FirstVerified != value))
				{
					this.OnFirstVerifiedChanging(value);
					this.SendPropertyChanging();
					this._FirstVerified = value;
					this.SendPropertyChanged("FirstVerified");
					this.OnFirstVerifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVerified", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastVerified
		{
			get
			{
				return this._LastVerified;
			}
			set
			{
				if ((this._LastVerified != value))
				{
					this.OnLastVerifiedChanging(value);
					this.SendPropertyChanging();
					this._LastVerified = value;
					this.SendPropertyChanged("LastVerified");
					this.OnLastVerifiedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
